require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'GAN_transfer' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'React', :path => '../node_modules/react-native'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'GAN_transferTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'GAN_transfer-tvOS' do
  # Pods for GAN_transfer-tvOS

  target 'GAN_transfer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
